branches:
  - master
  - master-release-test
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  
  $CHANGES
  
  ## Nuget-Downloads
  | Module | Nuget | 
  | ------ | -------------- | 
  | Base | [![Nuget](https://img.shields.io/badge/nuget-$RESOLVED_VERSION-informational)](https://www.nuget.org/packages/Litetex.JDKDownloader.Base/$RESOLVED_VERSION)|
  | Provider.AdoptOpenJDK | [![Nuget](https://img.shields.io/badge/nuget-$RESOLVED_VERSION-informational)](https://www.nuget.org/packages/Litetex.JDKDownloader.Provider.AdoptOpenJDK/$RESOLVED_VERSION)|
  
