name: Build Executables

on:
  workflow_dispatch:
#  push:
#    branches: [ develop ]
#    paths-ignore: 
#      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - '**.md'

jobs: 
  build_exec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        # https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
        # https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json
        os: 
          # Windows 64 bit - most users in the world run that
          - win-x64
          # Linux 64 bit - most servers in the world run that
          - linux-x64
          # Linux Musl 64 bit (for alpine linux) - most container images should have that
          - linux-musl-x64
          # Linux ARM 64 bit - most IoT devices (Rasperry Pi) run that (or ARM 32 bit)
          - linux-arm
          - linux-arm64
          # ...
          - osx-x64
          - osx-arm64
        configuration: [Release]
        project: [JDKDownloader]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish ${{ matrix.os }} ${{ matrix.configuration }} - dotnet publish 
      working-directory: src/${{ matrix.project }}
      run: dotnet publish -c ${{ matrix.configuration }} -r ${{ matrix.os }} /p:PublishSingleFile=true

      #Ignore pdb files
    - name: Pack ${{ matrix.os }} - Zip
      working-directory: src/${{ matrix.project }}/bin/${{ matrix.configuration }}/net5.0/${{ matrix.os }}/publish/
      run: zip -r ${{ matrix.project }}.zip . -x \*.pdb

    - name: Upload ${{ matrix.os }} - Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.project }}-${{ matrix.os }}.zip
        path: src/${{ matrix.project }}/bin/${{ matrix.configuration }}/net5.0/${{ matrix.os }}/publish/${{ matrix.project }}.zip
